# Generated by Django 5.2 on 2025-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_uploadedcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcv',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
