cv_texts = [
    "Backend developer with 4 years of experience in Django, RESTful APIs, PostgreSQL, and Docker.",
    "Frontend developer skilled in React, JavaScript, CSS, and responsive design principles.",
    "Data analyst proficient in SQL, Excel, Power BI, and data visualization techniques.",
    "Machine learning engineer with experience in Python, scikit-learn, and TensorFlow.",
    "DevOps engineer with CI/CD pipeline expertise, Jenkins, Docker, and Kubernetes.",
    "Mobile developer experienced in Flutter, Firebase, and cross-platform development.",
    "Cybersecurity specialist with knowledge of network security, ethical hacking, and SIEM tools.",
    "Full-stack developer skilled in MERN stack: MongoDB, Express, React, Node.js.",
    "Cloud engineer with hands-on experience in AWS services, EC2, S3, and IAM.",
    "Junior backend developer with Flask, SQLite, and Git experience from internships.",
    "NLP engineer with spaCy and BERT-based model development experience.",
    "UX/UI designer with proficiency in Figma, Adobe XD, and user testing principles.",
    "AI researcher with academic experience in neural networks and large language models.",
    "QA engineer with test automation knowledge using Selenium and PyTest.",
    "System administrator with Linux expertise, Bash scripting, and server monitoring tools.",
    "Business analyst with financial reporting experience and knowledge in Tableau.",
    "Game developer using Unity and C#, with 2 indie games published on Steam.",
    "RPA developer with UiPath, automating repetitive tasks in HR and Finance domains.",
    "Embedded systems developer with C/C++ knowledge, working on IoT devices.",
    "Data engineer with ETL pipeline development experience using Airflow and Spark."
]

job_descriptions = [
    "Looking for a Django backend developer with REST API skills and Docker experience.",
    "Hiring frontend developer with strong React and CSS expertise for UI/UX-heavy project.",
    "Seeking data analyst with Excel, SQL, and BI tools like Power BI or Tableau.",
    "Machine learning engineer needed for NLP projects using TensorFlow and Python.",
    "DevOps engineer role open with Kubernetes, Jenkins, and Docker knowledge required.",
    "Flutter mobile app developer needed for cross-platform app development.",
    "Looking for cybersecurity expert with penetration testing and network defense skills.",
    "Full-stack developer position using Node.js, Express, React, and MongoDB.",
    "AWS cloud engineer role requiring EC2, IAM, Lambda, and S3 experience.",
    "Backend intern familiar with Flask, REST APIs, and Git version control.",
    "Hiring NLP engineer with experience in transformers and spaCy.",
    "UI/UX designer needed for creating prototypes and running usability testing.",
    "AI researcher position focusing on deep learning and large-scale language models.",
    "QA automation engineer required with Selenium, Jenkins, and Python scripting.",
    "System administrator with Linux server experience and monitoring tools like Prometheus.",
    "We are hiring a business analyst to work on finance KPIs and Tableau dashboards.",
    "Game developer role for Unity-based casual mobile games.",
    "RPA developer needed for automation projects in supply chain and HR processes.",
    "Embedded systems developer required with real-time OS and ARM-based microcontrollers.",
    "Looking for a data engineer with Spark, Kafka, and ETL pipeline experience."
]
